accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('signup/', views.sign_up_view, name='sign_up'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug:slug>/', views.article_details, name='details'),
]

net_ninja/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def sign_up_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # Save the form to the database.
            # no need to use 'get_user()' because UserCreationForm has no such function
            user = form.save()
            # Log user in.
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Log in the user.
            user = form.get_user()
            login(request, user)

            # Redirect to article creation.
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))

            # Redirect to list of articles.
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        # logout function does not need user argument
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Article
# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_details(request, slug):
    article = get_object_or_404(Article, slug=slug)
    return render(request, 'articles/article_details.html', {'article': article})

@login_required()
def article_create(request):
    return render(request, 'articles/article_create.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
  <h1>Log In</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <p><input type="submit" value="Login"></p>
  </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}SignUp{% endblock %}

{% block content %}
  <h1>Sign Up</h1>
  <form class="site-form" action="{% url 'accounts:sign_up' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <p><input type="submit" value="Signup"></p>
  </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base.html' %}

{% block title %}
    Article Create
{% endblock %}

{% block content %}
    <div class="create-article">
        <h2>Create a new article.</h2>
    </div>
{% endblock %}

articles/templates/articles/article_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ article.text }}{% endblock %}

{% block content %}
<img src="{{ article.thumb.url }}"/>
<h1>{{ article.text }}</h1>
<div class="article">
  <h2><a href="{% url 'articles:details' article.slug %}">{{ article }}</a></h2>
  <p>{{ article.body }}</p>
  <p>{{ article.date }}</p>
</div>
{% endblock %}    

articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Articles{% endblock %}

{% block content %}
<h1>Article List</h1>
<div class="articles">
  {% for article in articles %}
    <div class="article">
      <h2><a href="{% url 'articles:details' article.slug %}">{{ article }}</a></h2>
      <p>{{ article.body|truncatechars:50 }}</p>
      <p>{{ article.date }}</p>
    </div>
  {% endfor %}
</div>
{% endblock %}    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <div id="content">
  <h1><a href="{% url 'articles:list'%}"><img src="{% static 'logo.png' %}"></a></h1>
  <nav>
    <ul>
      <li>
        <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
          {% csrf_token %}
          <button type="submit">Log Out</button>
        </form>
      </li>
    </ul>
  </nav>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
    {% block content %}{% endblock %}
  </div>
</body>
</html>